name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pytest V
      id: pytest-v
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Pytest V
        setup-command: pip install -r requirements.txt
        command: pytest -v
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTEST-V_RESULTS: "${{steps.pytest-v.outputs.result}}"
      with:
        runners: pytest-v
